#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'staircase' function below.
#
# The function accepts INTEGER n as parameter.
#

def staircase(n):
    #my logic
    for i in range(n-1,-1,-1):
        f=n-i
        print(i*" "+f*"#")
if __name__ == '__main__':
    n = int(input().strip())

    staircase(n)
